task:
   name: Verify Tests
   skip: "!changesInclude('**.py','pyproject.toml','poetry.lock')"
   env:
      matrix:
         - PYTHON_VERSION: 3.7
         - PYTHON_VERSION: 3.12-rc
      PYTHONPATH: /usr/lib/python3/dist-packages
   container:
      image: python:${PYTHON_VERSION}-slim
   install_script: |
     apt-get update
     apt-get install python3-cffi -y
     pip install poetry poethepoet --no-cache-dir
     poe install
     poe nltk_data
   test_script: poe test
