task:
   name: Verify Tests
   env:
      matrix:
         - PYTHON_VERSION: 3.7
         - PYTHON_VERSION: 3.12-rc
   container:
      image: python:${PYTHON_VERSION}-slim
   install_script: |
     apt-get upgrade
     apt-get install gcc -y
     pip install poetry poethepoet --no-cache-dir
     poe install
     poe nltk_data
   test_script: poe test
