[tool.poetry]
name = "supercatch"
version = "0.0.3"
description = "Corrector automático de exámenes"
authors = ["Daniel Pérez Ruiz <danielsp13>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
hypothesis = "^6.62.1"

[tool.poe.tasks]
install = "poetry install"
check = "python -m compileall src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
