name: Docker container Test

on:
  push:
      paths-ignore:
         - 'README.md'
         - 'docs/*'
         
jobs:
  docker_tests:
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout
           uses: actions/checkout@v3
             
         - name: Run Docker
           run: docker run -t -v `pwd`:/app/test danielsp13/supercatch
